// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package cz.cvut.fel.esw.server.proto;

/**
 * Protobuf type {@code Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            cz.cvut.fel.esw.server.proto.Request.GetCount.Builder subBuilder = null;
            if (msgCase_ == 1) {
              subBuilder = ((cz.cvut.fel.esw.server.proto.Request.GetCount) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(cz.cvut.fel.esw.server.proto.Request.GetCount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((cz.cvut.fel.esw.server.proto.Request.GetCount) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 1;
            break;
          }
          case 18: {
            cz.cvut.fel.esw.server.proto.Request.PostWords.Builder subBuilder = null;
            if (msgCase_ == 2) {
              subBuilder = ((cz.cvut.fel.esw.server.proto.Request.PostWords) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(cz.cvut.fel.esw.server.proto.Request.PostWords.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((cz.cvut.fel.esw.server.proto.Request.PostWords) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cz.cvut.fel.esw.server.proto.Request.class, cz.cvut.fel.esw.server.proto.Request.Builder.class);
  }

  public interface GetCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request.GetCount)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Request.GetCount}
   */
  public static final class GetCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request.GetCount)
      GetCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCount.newBuilder() to construct.
    private GetCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCount() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_GetCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_GetCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cz.cvut.fel.esw.server.proto.Request.GetCount.class, cz.cvut.fel.esw.server.proto.Request.GetCount.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cz.cvut.fel.esw.server.proto.Request.GetCount)) {
        return super.equals(obj);
      }
      cz.cvut.fel.esw.server.proto.Request.GetCount other = (cz.cvut.fel.esw.server.proto.Request.GetCount) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cz.cvut.fel.esw.server.proto.Request.GetCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cz.cvut.fel.esw.server.proto.Request.GetCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request.GetCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request.GetCount)
        cz.cvut.fel.esw.server.proto.Request.GetCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_GetCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_GetCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cz.cvut.fel.esw.server.proto.Request.GetCount.class, cz.cvut.fel.esw.server.proto.Request.GetCount.Builder.class);
      }

      // Construct using cz.cvut.fel.esw.server.proto.Request.GetCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_GetCount_descriptor;
      }

      @java.lang.Override
      public cz.cvut.fel.esw.server.proto.Request.GetCount getDefaultInstanceForType() {
        return cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance();
      }

      @java.lang.Override
      public cz.cvut.fel.esw.server.proto.Request.GetCount build() {
        cz.cvut.fel.esw.server.proto.Request.GetCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cz.cvut.fel.esw.server.proto.Request.GetCount buildPartial() {
        cz.cvut.fel.esw.server.proto.Request.GetCount result = new cz.cvut.fel.esw.server.proto.Request.GetCount(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cz.cvut.fel.esw.server.proto.Request.GetCount) {
          return mergeFrom((cz.cvut.fel.esw.server.proto.Request.GetCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cz.cvut.fel.esw.server.proto.Request.GetCount other) {
        if (other == cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cz.cvut.fel.esw.server.proto.Request.GetCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cz.cvut.fel.esw.server.proto.Request.GetCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request.GetCount)
    }

    // @@protoc_insertion_point(class_scope:Request.GetCount)
    private static final cz.cvut.fel.esw.server.proto.Request.GetCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cz.cvut.fel.esw.server.proto.Request.GetCount();
    }

    public static cz.cvut.fel.esw.server.proto.Request.GetCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCount>
        PARSER = new com.google.protobuf.AbstractParser<GetCount>() {
      @java.lang.Override
      public GetCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request.GetCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostWordsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request.PostWords)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Request.PostWords}
   */
  public static final class PostWords extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request.PostWords)
      PostWordsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostWords.newBuilder() to construct.
    private PostWords(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostWords() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PostWords();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostWords(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_PostWords_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_PostWords_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cz.cvut.fel.esw.server.proto.Request.PostWords.class, cz.cvut.fel.esw.server.proto.Request.PostWords.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cz.cvut.fel.esw.server.proto.Request.PostWords)) {
        return super.equals(obj);
      }
      cz.cvut.fel.esw.server.proto.Request.PostWords other = (cz.cvut.fel.esw.server.proto.Request.PostWords) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cz.cvut.fel.esw.server.proto.Request.PostWords parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cz.cvut.fel.esw.server.proto.Request.PostWords prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request.PostWords}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request.PostWords)
        cz.cvut.fel.esw.server.proto.Request.PostWordsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_PostWords_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_PostWords_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cz.cvut.fel.esw.server.proto.Request.PostWords.class, cz.cvut.fel.esw.server.proto.Request.PostWords.Builder.class);
      }

      // Construct using cz.cvut.fel.esw.server.proto.Request.PostWords.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_PostWords_descriptor;
      }

      @java.lang.Override
      public cz.cvut.fel.esw.server.proto.Request.PostWords getDefaultInstanceForType() {
        return cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance();
      }

      @java.lang.Override
      public cz.cvut.fel.esw.server.proto.Request.PostWords build() {
        cz.cvut.fel.esw.server.proto.Request.PostWords result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cz.cvut.fel.esw.server.proto.Request.PostWords buildPartial() {
        cz.cvut.fel.esw.server.proto.Request.PostWords result = new cz.cvut.fel.esw.server.proto.Request.PostWords(this);
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cz.cvut.fel.esw.server.proto.Request.PostWords) {
          return mergeFrom((cz.cvut.fel.esw.server.proto.Request.PostWords)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cz.cvut.fel.esw.server.proto.Request.PostWords other) {
        if (other == cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cz.cvut.fel.esw.server.proto.Request.PostWords parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cz.cvut.fel.esw.server.proto.Request.PostWords) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request.PostWords)
    }

    // @@protoc_insertion_point(class_scope:Request.PostWords)
    private static final cz.cvut.fel.esw.server.proto.Request.PostWords DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cz.cvut.fel.esw.server.proto.Request.PostWords();
    }

    public static cz.cvut.fel.esw.server.proto.Request.PostWords getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostWords>
        PARSER = new com.google.protobuf.AbstractParser<PostWords>() {
      @java.lang.Override
      public PostWords parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostWords(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostWords> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostWords> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request.PostWords getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    GETCOUNT(1),
    POSTWORDS(2),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return GETCOUNT;
        case 2: return POSTWORDS;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int GETCOUNT_FIELD_NUMBER = 1;
  /**
   * <code>.Request.GetCount getCount = 1;</code>
   * @return Whether the getCount field is set.
   */
  @java.lang.Override
  public boolean hasGetCount() {
    return msgCase_ == 1;
  }
  /**
   * <code>.Request.GetCount getCount = 1;</code>
   * @return The getCount.
   */
  @java.lang.Override
  public cz.cvut.fel.esw.server.proto.Request.GetCount getGetCount() {
    if (msgCase_ == 1) {
       return (cz.cvut.fel.esw.server.proto.Request.GetCount) msg_;
    }
    return cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance();
  }
  /**
   * <code>.Request.GetCount getCount = 1;</code>
   */
  @java.lang.Override
  public cz.cvut.fel.esw.server.proto.Request.GetCountOrBuilder getGetCountOrBuilder() {
    if (msgCase_ == 1) {
       return (cz.cvut.fel.esw.server.proto.Request.GetCount) msg_;
    }
    return cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance();
  }

  public static final int POSTWORDS_FIELD_NUMBER = 2;
  /**
   * <code>.Request.PostWords postWords = 2;</code>
   * @return Whether the postWords field is set.
   */
  @java.lang.Override
  public boolean hasPostWords() {
    return msgCase_ == 2;
  }
  /**
   * <code>.Request.PostWords postWords = 2;</code>
   * @return The postWords.
   */
  @java.lang.Override
  public cz.cvut.fel.esw.server.proto.Request.PostWords getPostWords() {
    if (msgCase_ == 2) {
       return (cz.cvut.fel.esw.server.proto.Request.PostWords) msg_;
    }
    return cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance();
  }
  /**
   * <code>.Request.PostWords postWords = 2;</code>
   */
  @java.lang.Override
  public cz.cvut.fel.esw.server.proto.Request.PostWordsOrBuilder getPostWordsOrBuilder() {
    if (msgCase_ == 2) {
       return (cz.cvut.fel.esw.server.proto.Request.PostWords) msg_;
    }
    return cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgCase_ == 1) {
      output.writeMessage(1, (cz.cvut.fel.esw.server.proto.Request.GetCount) msg_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (cz.cvut.fel.esw.server.proto.Request.PostWords) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (cz.cvut.fel.esw.server.proto.Request.GetCount) msg_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (cz.cvut.fel.esw.server.proto.Request.PostWords) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cz.cvut.fel.esw.server.proto.Request)) {
      return super.equals(obj);
    }
    cz.cvut.fel.esw.server.proto.Request other = (cz.cvut.fel.esw.server.proto.Request) obj;

    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 1:
        if (!getGetCount()
            .equals(other.getGetCount())) return false;
        break;
      case 2:
        if (!getPostWords()
            .equals(other.getPostWords())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (msgCase_) {
      case 1:
        hash = (37 * hash) + GETCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getGetCount().hashCode();
        break;
      case 2:
        hash = (37 * hash) + POSTWORDS_FIELD_NUMBER;
        hash = (53 * hash) + getPostWords().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cz.cvut.fel.esw.server.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cz.cvut.fel.esw.server.proto.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Request)
      cz.cvut.fel.esw.server.proto.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cz.cvut.fel.esw.server.proto.Request.class, cz.cvut.fel.esw.server.proto.Request.Builder.class);
    }

    // Construct using cz.cvut.fel.esw.server.proto.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cz.cvut.fel.esw.server.proto.Schema.internal_static_Request_descriptor;
    }

    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request getDefaultInstanceForType() {
      return cz.cvut.fel.esw.server.proto.Request.getDefaultInstance();
    }

    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request build() {
      cz.cvut.fel.esw.server.proto.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request buildPartial() {
      cz.cvut.fel.esw.server.proto.Request result = new cz.cvut.fel.esw.server.proto.Request(this);
      if (msgCase_ == 1) {
        if (getCountBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = getCountBuilder_.build();
        }
      }
      if (msgCase_ == 2) {
        if (postWordsBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = postWordsBuilder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cz.cvut.fel.esw.server.proto.Request) {
        return mergeFrom((cz.cvut.fel.esw.server.proto.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cz.cvut.fel.esw.server.proto.Request other) {
      if (other == cz.cvut.fel.esw.server.proto.Request.getDefaultInstance()) return this;
      switch (other.getMsgCase()) {
        case GETCOUNT: {
          mergeGetCount(other.getGetCount());
          break;
        }
        case POSTWORDS: {
          mergePostWords(other.getPostWords());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cz.cvut.fel.esw.server.proto.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cz.cvut.fel.esw.server.proto.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        cz.cvut.fel.esw.server.proto.Request.GetCount, cz.cvut.fel.esw.server.proto.Request.GetCount.Builder, cz.cvut.fel.esw.server.proto.Request.GetCountOrBuilder> getCountBuilder_;
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     * @return Whether the getCount field is set.
     */
    @java.lang.Override
    public boolean hasGetCount() {
      return msgCase_ == 1;
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     * @return The getCount.
     */
    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request.GetCount getGetCount() {
      if (getCountBuilder_ == null) {
        if (msgCase_ == 1) {
          return (cz.cvut.fel.esw.server.proto.Request.GetCount) msg_;
        }
        return cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance();
      } else {
        if (msgCase_ == 1) {
          return getCountBuilder_.getMessage();
        }
        return cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance();
      }
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     */
    public Builder setGetCount(cz.cvut.fel.esw.server.proto.Request.GetCount value) {
      if (getCountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        getCountBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     */
    public Builder setGetCount(
        cz.cvut.fel.esw.server.proto.Request.GetCount.Builder builderForValue) {
      if (getCountBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        getCountBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     */
    public Builder mergeGetCount(cz.cvut.fel.esw.server.proto.Request.GetCount value) {
      if (getCountBuilder_ == null) {
        if (msgCase_ == 1 &&
            msg_ != cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance()) {
          msg_ = cz.cvut.fel.esw.server.proto.Request.GetCount.newBuilder((cz.cvut.fel.esw.server.proto.Request.GetCount) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 1) {
          getCountBuilder_.mergeFrom(value);
        } else {
          getCountBuilder_.setMessage(value);
        }
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     */
    public Builder clearGetCount() {
      if (getCountBuilder_ == null) {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
        }
        getCountBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     */
    public cz.cvut.fel.esw.server.proto.Request.GetCount.Builder getGetCountBuilder() {
      return getGetCountFieldBuilder().getBuilder();
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     */
    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request.GetCountOrBuilder getGetCountOrBuilder() {
      if ((msgCase_ == 1) && (getCountBuilder_ != null)) {
        return getCountBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 1) {
          return (cz.cvut.fel.esw.server.proto.Request.GetCount) msg_;
        }
        return cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance();
      }
    }
    /**
     * <code>.Request.GetCount getCount = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cz.cvut.fel.esw.server.proto.Request.GetCount, cz.cvut.fel.esw.server.proto.Request.GetCount.Builder, cz.cvut.fel.esw.server.proto.Request.GetCountOrBuilder> 
        getGetCountFieldBuilder() {
      if (getCountBuilder_ == null) {
        if (!(msgCase_ == 1)) {
          msg_ = cz.cvut.fel.esw.server.proto.Request.GetCount.getDefaultInstance();
        }
        getCountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cz.cvut.fel.esw.server.proto.Request.GetCount, cz.cvut.fel.esw.server.proto.Request.GetCount.Builder, cz.cvut.fel.esw.server.proto.Request.GetCountOrBuilder>(
                (cz.cvut.fel.esw.server.proto.Request.GetCount) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 1;
      onChanged();;
      return getCountBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        cz.cvut.fel.esw.server.proto.Request.PostWords, cz.cvut.fel.esw.server.proto.Request.PostWords.Builder, cz.cvut.fel.esw.server.proto.Request.PostWordsOrBuilder> postWordsBuilder_;
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     * @return Whether the postWords field is set.
     */
    @java.lang.Override
    public boolean hasPostWords() {
      return msgCase_ == 2;
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     * @return The postWords.
     */
    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request.PostWords getPostWords() {
      if (postWordsBuilder_ == null) {
        if (msgCase_ == 2) {
          return (cz.cvut.fel.esw.server.proto.Request.PostWords) msg_;
        }
        return cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return postWordsBuilder_.getMessage();
        }
        return cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance();
      }
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     */
    public Builder setPostWords(cz.cvut.fel.esw.server.proto.Request.PostWords value) {
      if (postWordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        postWordsBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     */
    public Builder setPostWords(
        cz.cvut.fel.esw.server.proto.Request.PostWords.Builder builderForValue) {
      if (postWordsBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        postWordsBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     */
    public Builder mergePostWords(cz.cvut.fel.esw.server.proto.Request.PostWords value) {
      if (postWordsBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance()) {
          msg_ = cz.cvut.fel.esw.server.proto.Request.PostWords.newBuilder((cz.cvut.fel.esw.server.proto.Request.PostWords) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          postWordsBuilder_.mergeFrom(value);
        } else {
          postWordsBuilder_.setMessage(value);
        }
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     */
    public Builder clearPostWords() {
      if (postWordsBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        postWordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     */
    public cz.cvut.fel.esw.server.proto.Request.PostWords.Builder getPostWordsBuilder() {
      return getPostWordsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     */
    @java.lang.Override
    public cz.cvut.fel.esw.server.proto.Request.PostWordsOrBuilder getPostWordsOrBuilder() {
      if ((msgCase_ == 2) && (postWordsBuilder_ != null)) {
        return postWordsBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (cz.cvut.fel.esw.server.proto.Request.PostWords) msg_;
        }
        return cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance();
      }
    }
    /**
     * <code>.Request.PostWords postWords = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cz.cvut.fel.esw.server.proto.Request.PostWords, cz.cvut.fel.esw.server.proto.Request.PostWords.Builder, cz.cvut.fel.esw.server.proto.Request.PostWordsOrBuilder> 
        getPostWordsFieldBuilder() {
      if (postWordsBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = cz.cvut.fel.esw.server.proto.Request.PostWords.getDefaultInstance();
        }
        postWordsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cz.cvut.fel.esw.server.proto.Request.PostWords, cz.cvut.fel.esw.server.proto.Request.PostWords.Builder, cz.cvut.fel.esw.server.proto.Request.PostWordsOrBuilder>(
                (cz.cvut.fel.esw.server.proto.Request.PostWords) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();;
      return postWordsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Request)
  }

  // @@protoc_insertion_point(class_scope:Request)
  private static final cz.cvut.fel.esw.server.proto.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cz.cvut.fel.esw.server.proto.Request();
  }

  public static cz.cvut.fel.esw.server.proto.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cz.cvut.fel.esw.server.proto.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

