// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package cz.cvut.fel.esw.server.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Always present
   * </pre>
   *
   * <code>.Response.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Always present
   * </pre>
   *
   * <code>.Response.Status status = 1;</code>
   * @return The status.
   */
  cz.cvut.fel.esw.server.proto.Response.Status getStatus();

  /**
   * <code>int32 counter = 2;</code>
   * @return The counter.
   */
  int getCounter();

  /**
   * <code>string errMsg = 3;</code>
   * @return The errMsg.
   */
  java.lang.String getErrMsg();
  /**
   * <code>string errMsg = 3;</code>
   * @return The bytes for errMsg.
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();
}
