// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package cz.cvut.fel.esw.server.proto;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_GetCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_GetCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_PostWords_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_PostWords_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\"\207\001\n\007Request\022%\n\010getCount\030\001" +
      " \001(\0132\021.Request.GetCountH\000\022\'\n\tpostWords\030\002" +
      " \001(\0132\022.Request.PostWordsH\000\032\n\n\010GetCount\032\031" +
      "\n\tPostWords\022\014\n\004data\030\001 \001(\014B\005\n\003msg\"j\n\010Resp" +
      "onse\022 \n\006status\030\001 \001(\0162\020.Response.Status\022\017" +
      "\n\007counter\030\002 \001(\005\022\016\n\006errMsg\030\003 \001(\t\"\033\n\006Statu" +
      "s\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001B \n\034cz.cvut.fel.esw." +
      "server.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "GetCount", "PostWords", "Msg", });
    internal_static_Request_GetCount_descriptor =
      internal_static_Request_descriptor.getNestedTypes().get(0);
    internal_static_Request_GetCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_GetCount_descriptor,
        new java.lang.String[] { });
    internal_static_Request_PostWords_descriptor =
      internal_static_Request_descriptor.getNestedTypes().get(1);
    internal_static_Request_PostWords_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_PostWords_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Status", "Counter", "ErrMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
